### ISSUE TITLE
🐛 [Bug Report]:  register wont complete

### ISSUE THREAD

**Issue by andsim** [WoW-CMS/BlizzCMS#123] opened 2023-07-22 04:53 UTC
### BlizzCMS Version

2.0.0-beta 2

### Emulator

TrinityCore

### PHP Version

PHP 7.4

### Operating system

Windows

### Web server

Apache

### Database

MariaDB 11.0.1

### What happened?

wont register, no error just reload

### How can the issue be reproduced?

not sure why is this happen

**Comment by sayghteight** [comment] 2023-08-02 13:07
Thank you for reporting this issue with registration in BlizzCMS Version 2.0.0-beta 2. We apologize for any inconvenience this may be causing. Our development team is aware of the problem, and we are currently working to identify and address the root cause. We appreciate your patience as we tackle this issue. 

We will keep this Issue updated with any progress or solutions we have. If you have any additional information or details that could be helpful in resolving the problem, please feel free to provide them here. 

Thank you for your collaboration in improving BlizzCMS.

**Comment by sayghteight** [comment] 2023-08-07 13:55
We appreciate your earlier report concerning the registration issue in BlizzCMS Version 2.0.0-beta 2 and want to thank you for your proactive involvement in improving our platform.

Following our thorough investigation, we regret to inform you that we have been unable to reproduce the issue you reported. Despite our best efforts, the problem you encountered did not manifest in our testing environment. As a result, we will be closing this particular issue.

We understand that this outcome may be disappointing, and we apologize for any inconvenience this may have caused. We value your dedication to ensuring the quality of our software, and your feedback remains crucial to us. Please don't hesitate to reach out if you encounter any other issues or have suggestions for improvement in the future.

Thank you once again for your collaboration and understanding. We look forward to your continued engagement in enhancing the BlizzCMS experience.

**Closed by sayghteight** 2023-08-07 13:55 UTC
Labels: bug
