### ISSUE TITLE
🐛 [Bug Report]: 

### ISSUE THREAD

**Issue by yuanf225** [WoW-CMS/BlizzCMS#107] opened 2023-01-04 13:17 UTC
### BlizzCMS Version

2.0

### Emulator

AzerothCore

### PHP Version

PHP 7.4

### Operating system

Linux

### Web server

Apache

### Database

MariaDB 10.7

### What happened?

I just tried to use version 2.0. When I filled in the site name and selected the next step of the simulator, I prompted: PAGE NOT FOUND.
The page you requested could not be found

### How can the issue be reproduced?

https://www.tbcstar.com/install/cms

### Screenshots

![image](https://user-images.githubusercontent.com/43561197/210563100-9e43d38b-e932-4071-9952-1ebcacc3230e.png)

**Comment by yuanf225** [comment] 2023-01-04 13:19
This makes the admin/user page inaccessible: permission is denied.
You don't have permission to access this page!

**Comment by yuanf225** [comment] 2023-01-07 13:04
@DZywolf  Please check this  issue, thank you.

**Comment by wolone** [comment] 2023-02-04 18:07
The same problem occurs in this step for both new and existing accounts

**Comment by sayghteight** [comment] 2023-07-16 13:48
Since we have not been able to reproduce this error, we proceed to close the Issue, if you have this problem again, let us know.

**Closed by sayghteight** 2023-07-16 13:48 UTC
Labels: bug
