### ISSUE TITLE
[Bug Report]: Soap Issue.Connecting but have error

### ISSUE THREAD

**Issue by cutdachez** [WoW-CMS/BlizzCMS#93] opened 2022-10-24 18:50 UTC
### What operating system are you using?

Windows

### What version of PHP do you use?

PHP 7.x

### Where did you get the CMS code?

Github

### Where are you trying to install the CMS?

Localhost

### Which emulator are you using and which version?

SkyFire

### Describe the bug

Checksoap gives error. Does not say can not connect Like I have seen previously. Or is this not connecting?

Using MoP Emucoach premium.
Cms version 1.1.0

### How can I reproduce the problem?

Not sure how to reproduce

### Screenshots

![image](https://user-images.githubusercontent.com/43968878/197602739-57ab1386-6956-42b6-8cfc-e1cd678010d5.png)

**Comment by sayghteight** [comment] 2022-10-25 10:53
Hello,

It is not a bug as such, check that you have the correct connection parameters, remember that for the soap I think it does not allow communication through localhost or 127.0.0.1 and try putting the IP of your realm.

If you continue, check your world settings and if you have the soap plugin enabled.

**Comment by cutdachez** [comment] 2022-10-26 14:16
The error above does not appear to be a connection to soap issue. This is what it says when it is connection to soap issue. Is says cannot connect. Yes it is enabled in config and php.ini . Has console or admin/gm permissions.

![image](https://user-images.githubusercontent.com/43968878/198050359-0b5b7739-bc23-4976-8810-9c6a59024f75.png)

**Comment by sayghteight** [comment] 2022-10-26 15:12
commit: https://github.com/WoW-CMS/BlizzCMS/commit/4de03349c0848105246c0f0c5e1329d79845caa8

Test this change in local, save the model.

**Comment by cutdachez** [comment] 2022-10-26 15:22
That fixed it. Great Job! Thanks

**Comment by sayghteight** [comment] 2022-10-26 16:33
Okay, fixed in #94 closed issue

**Closed by sayghteight** 2022-10-26 16:33 UTC
Labels: help wanted
